INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Dec/2021 19:09:21] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [16/Dec/2021 19:09:21] "GET /getimage/IMG_5375.JPG HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Dec/2021 19:09:42] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [16/Dec/2021 19:09:42] "GET /getimage/sdf.jpeg HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [16/Dec/2021 19:16:38] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [16/Dec/2021 19:16:38] "GET /getimage/33ece3f5-da14-421c-9dc6-df043f96f741.JPG HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Dec/2021 20:10:22] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [19/Dec/2021 20:10:22] "GET /getimage/cat.3.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Dec/2021 21:59:16] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
INFO:werkzeug:127.0.0.1 - - [19/Dec/2021 22:05:07] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [19/Dec/2021 22:05:07] "GET /getimage/cat.10.jpg HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/Users/sebastianstraub/Documents/Image_Recognition_Visualize/server.py', reloading
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [22/Dec/2021 11:26:08] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [22/Dec/2021 11:26:08] "GET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 13:55:28] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 13:55:28] "GET /getimage/download.jpeg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:16:37] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:16:37] "GET /getimage/sdf.jpeg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:18:52] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:19:09] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:20:17] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:29:35] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:29:35] "GET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:30:02] "[31m[1mPOST /upload HTTP/1.1[0m" 400 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:31:11] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:31:11] "GET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:32:02] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:32:03] "GET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:32:50] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:32:50] "GET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:33:32] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:33:32] "GET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:36:18] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 14:36:18] "GET /getimage/sdf-removebg-preview.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 15:15:16] "[31m[1mGET /upload HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 15:15:16] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 15:19:15] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 15:19:15] "GET /getimage/puppy-1903313_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 15:20:24] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 15:20:24] "GET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 15:22:34] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 15:22:34] "GET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 15:22:47] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 15:22:47] "GET /getimage/puppy-1903313_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 16:34:13] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 16:34:13] "GET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 21:43:44] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 21:43:44] "GET /getimage/puppy-1903313_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 22:42:43] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 22:42:43] "GET /getimage/puppy-1903313_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 22:50:30] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 22:50:30] "GET /getimage/puppy-1903313_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 22:53:37] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 22:53:37] "GET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 22:55:29] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 22:55:29] "GET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:16:54] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:16:54] "GET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:18:05] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:18:05] "GET /getimage/puppy-1903313_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:19:19] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:19:19] "GET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:20:01] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:20:01] "GET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:21:21] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:21:21] "GET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1" 200 -
ERROR:server:Exception on /upload [POST]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 91, in upload_file
    rmbg.remove_background_from_img_file(filepath)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/removebg/removebg.py", line 31, in remove_background_from_img_file
    response.raise_for_status()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 402 Client Error: Payment Required for url: https://api.remove.bg/v1.0/removebg
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:32:43] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
ERROR:server:Exception on /upload [POST]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 91, in upload_file
    rmbg.remove_background_from_img_file(filepath)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/removebg/removebg.py", line 31, in remove_background_from_img_file
    response.raise_for_status()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 402 Client Error: Payment Required for url: https://api.remove.bg/v1.0/removebg
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:35:16] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
ERROR:server:Exception on /upload [POST]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 91, in upload_file
    rmbg.remove_background_from_img_file(filepath)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/removebg/removebg.py", line 31, in remove_background_from_img_file
    response.raise_for_status()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 402 Client Error: Payment Required for url: https://api.remove.bg/v1.0/removebg
INFO:werkzeug:127.0.0.1 - - [28/Dec/2021 23:36:48] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:20:57] "[31m[1mGET /upload HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:20:57] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:21:00] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:21:14] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/dog-3277416_1280.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/dog-3277416_1280.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:21:14] "[35m[1mGET /getimage/dog-3277416_1280.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:21:36] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/cocker-spaniel-2785074_640.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/cocker-spaniel-2785074_640.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:21:36] "[35m[1mGET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:21:51] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/cocker-spaniel-2785074_640.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/cocker-spaniel-2785074_640.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:21:52] "[35m[1mGET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:22:00] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/cocker-spaniel-2785074_640.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/cocker-spaniel-2785074_640.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 17:22:00] "[35m[1mGET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:21:58] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/cat-g2c34ccd26_1280.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/cat-g2c34ccd26_1280.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:21:58] "[35m[1mGET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:22:18] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/cat-g2c34ccd26_1280.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/cat-g2c34ccd26_1280.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:22:18] "[35m[1mGET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:23:28] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/cat-g2c34ccd26_1280.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/cat-g2c34ccd26_1280.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:23:28] "[35m[1mGET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:23:45] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/puppy-1903313_1280.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/puppy-1903313_1280.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:23:45] "[35m[1mGET /getimage/puppy-1903313_1280.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:25:50] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/dog-3277416_1280.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/dog-3277416_1280.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:25:50] "[35m[1mGET /getimage/dog-3277416_1280.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:27:32] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/cocker-spaniel-2785074_640.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/cocker-spaniel-2785074_640.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:27:32] "[35m[1mGET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:29:08] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/puppy-1903313_1280.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/puppy-1903313_1280.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:29:08] "[35m[1mGET /getimage/puppy-1903313_1280.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:29:55] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/cat-g2c34ccd26_1280.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/cat-g2c34ccd26_1280.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:29:55] "[35m[1mGET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:30:33] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/cat-g2c34ccd26_1280.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/cat-g2c34ccd26_1280.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:30:33] "[35m[1mGET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:31:13] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
ERROR:server:Exception on /getimage/cat-g2c34ccd26_1280.jpg [GET]
Traceback (most recent call last):
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bastistr/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 66, in getimage
    encoded_img_data = get_base64_encoded_image(filepath)
  File "/Users/bastistr/Documents/dev/Image_Recognition_Visualize/server.py", line 55, in get_base64_encoded_image
    with open(image_path, "rb") as img_file:
FileNotFoundError: [Errno 2] No such file or directory: 'pictures/cat-g2c34ccd26_1280.jpg'
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:31:13] "[35m[1mGET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:33:19] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:33:19] "GET /getimage/puppy-1903313_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:33:38] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:33:38] "GET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:34:27] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:34:27] "GET /getimage/sdf-removebg-preview.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:35:00] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:35:00] "GET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:53:47] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2021 20:53:47] "GET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 02:55:32] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 02:55:32] "GET /getimage/dog-3277416_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:04:07] "[31m[1mGET /upload HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:04:14] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:06:11] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:06:11] "GET /getimage/cat-g2c34ccd26_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:11:37] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:11:37] "GET /getimage/cocker-spaniel-2785074_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:15:18] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:15:18] "GET /getimage/puppy-1207816_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:15:29] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:15:29] "GET /getimage/maltese-1123016_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:25:29] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 03:25:29] "GET /getimage/labrador-retriever-1210559_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:04:05] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:04:06] "GET /getimage/maltese-1123016_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:20:25] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:21:26] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:21:26] "GET /getimage/labrador-retriever-1210559_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:22:51] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:22:51] "GET /getimage/labrador-retriever-1210559_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:23:26] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:23:26] "GET /getimage/puppy-1903313_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:25:39] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:25:39] "GET /getimage/puppy-1207816_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:27:49] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:27:49] "GET /getimage/sdf-removebg-preview.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:29:08] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:29:08] "GET /getimage/sdf-removebg-preview.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:30:46] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:30:46] "GET /getimage/maltese-1123016_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:33:19] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:33:19] "GET /getimage/maltese-1123016_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:34:49] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:34:49] "GET /getimage/puppy-1903313_1280.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:37:03] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:37:03] "GET /getimage/animal-3782188.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:39:06] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:39:06] "GET /getimage/animal-3782188.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:40:05] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:40:05] "GET /getimage/animal-3782188.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:41:44] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:41:44] "GET /getimage/animal-3782188.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:42:25] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:42:25] "GET /getimage/labrador-retriever-1210559_640.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:48:28] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:48:28] "GET /getimage/animal-3782188.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:49:15] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2021 17:49:16] "GET /getimage/animal-3782188.jpg HTTP/1.1" 200 -
